#+author: Indigo Paige
#+title:  indigopaige.blog

* Indigo Paige                                                         :blog:
:PROPERTIES:
:AUTHOR:   Indigo Paige
:DATE:     [2026-09-10 Thu]
:PATH:     indigo-paige
:END:

** Indigo Paige
My name indigo, but please, call me indy. I'm a self taught programming
amateur who prides themselves on creativity, and personality.
** Oxb
Oxb (org export blog) is a small personalized (not meant for public use)
software I created to turn .org documents into a full blog website.
That is what this website is hosted on. See more about oxb [[https:indigopaige.blog/oxb][here]].
* Oxb                                                                  :blog:
:PROPERTIES:
:AUTHOR:   Indigo Paige
:DATE:     [2026-09-11 Fri]
:PATH:     oxb
:END:

Oxb is my personalized blog-generating org tool. It's currently unfinished,
only implementing features that I personally use for my blogs. However,
this doesn't stop anyone from making a pull request. I would love to make
this fully featured in the future.

Oxb stands for org export blog. Which seems to make sense. It's a nix-based
project which means it's fairly easy to deploy, as long as you know how to
use nix flakes. It's also a static site generator. Which means as long as
you build it with nix once, it will give you a folder containing your site.

The static site generation is also quite handy for making your website using
github pages, or similar. Just use an action to build your website, and it
should be easy to deploy it from there.
